begin_with_yourself/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
    path(
        'instruction/',
        views.AboutInstructionView.as_view(),
        name='instruction'
    )
]

begin_with_yourself/begin_with_yourself/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('news/', include('news.urls', namespace='news')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls', namespace='users'))
]

begin_with_yourself/main/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('map/', views.map, name='map'),
    path('profile/<int:user_id>', views.profile, name='profile'),
    path('crate_idea/', views.create_idea, name='create_idea'),
    path('idead_edit/', views.idea_edit, name='idea_edit'),
    path('idea_detail/<int:idea_id>', views.idea_detail, name='idea_detail'),
    path('', views.main, name='index')
]

begin_with_yourself/news/urls.py
from django.urls import path

from . import views


app_name = 'news'

urlpatterns = [
    path('all/', views.news, name='news')
]

begin_with_yourself/users/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path

from . import views

app_name = 'users'


urlpatterns = [
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'
    ),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
]

begin_with_yourself/about/models.py
from django.db import models

# Create your models here.

begin_with_yourself/main/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

IDEA_SCALE = [
    ('ПОД', 'Подъезд'),
    ('ДВО', 'Двор'),
    ('РАЙ', 'Район'),
    ('ГОР', 'Город'),
    ('ОБЛ', 'Область'),
    ('СТР', 'Страна')
]


class IdeaModel(models.Model):

    text = models.CharField(
        verbose_name='Текст',
        help_text='Описание вашей идеи.',
        max_length=5000
    )

    pub_date = models.DateTimeField(auto_now_add=True)

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='ideas'
    )

    scale = models.CharField(
        max_length=3,
        choices=IDEA_SCALE,
        default=IDEA_SCALE[0][0]
    )

    coordinate_x = models.FloatField(
        verbose_name='Координаты места',
        help_text='По этим коориднатам будет отражаться метка вашей идеи.',
        default=None
    )

    coordinate_y = models.FloatField(
        verbose_name='Координаты места',
        help_text='По этим коориднатам будет отражаться метка вашей идеи.',
        default=None
    )

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
        return self.text[:15]

begin_with_yourself/news/models.py
from django.db import models

# Create your models here.

begin_with_yourself/users/models.py
from django.db import models

# Create your models here.

begin_with_yourself/main/forms.py
from django import forms

from .models import IdeaModel


class CreateIdea(forms.ModelForm):
    class Meta:

        model = IdeaModel

        fields = ('text', 'scale', 'coordinate_x', 'coordinate_y')

begin_with_yourself/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class CreatForm(UserCreationForm):
    """Форма регистрации."""
    class Meta(UserCreationForm.Meta):
        model = User

        fields = ('first_name', 'last_name', 'username', 'email')

begin_with_yourself/about/views.py
from django.views.generic import TemplateView


class AboutAuthorView(TemplateView):
    """Страница информации об авторе."""

    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    """Страница информации об технологиях использованых в проекте."""

    template_name = 'about/tech.html'


class AboutInstructionView(TemplateView):
    """Страница информации об технологиях использованых в проекте."""

    template_name = 'about/instruction.html'

begin_with_yourself/main/views.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

from .models import User, IdeaModel
from .forms import CreateIdea
from .utils import generate_map


def main(request):
    """Главная страница."""

    return render(request, 'main/index.html')


@login_required
def map(request):
    """Страница с картой."""
    generate_map()

    return render(request, 'main/map.html')


@login_required
def profile(request, user_id):
    """Страница пользователя."""
    user = get_object_or_404(User, id=user_id)
    all_ideas = user.ideas.all()

    paginator = Paginator(all_ideas, 10)

    page_number = request.GET.get('page')

    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj
    }

    return render(request, 'main/profile.html', context)


def idea_detail(request, idea_id):
    idea = get_object_or_404(IdeaModel, pk=idea_id)

    context = {
        'idea': idea
    }
    return render(request, 'main/idea_detail.html', context)


@login_required
def create_idea(request):
    """Страница создания поста."""

    form = CreateIdea(request.POST or None)

    if form.is_valid():
        form = form.save(commit=False)
        form.author = request.user
        form.save()
        return redirect('main:profile', request.user.id)

    return render(request, 'main/create_idea.html', {'form': form})


@login_required
def idea_edit(request, idea_id):
    post = get_object_or_404(IdeaModel, id=idea_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id=idea_id)

    form = CreateIdea(request.POST or None, instance=post)

    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('main:profile', user_id=request.user.id)

    is_edit = True
    return render(
        request,
        'main/create_idea.html',
        {'is_edit': is_edit, 'form': form})

begin_with_yourself/news/views.py
from django.shortcuts import render
from django.core.paginator import Paginator

from main.models import IdeaModel


def news(request):
    """Страница последних идей."""
    list_idea = IdeaModel.objects.select_related('author').all()

    paginator = Paginator(list_idea, 10)

    page_number = request.GET.get('page')

    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj
    }
    return render(request, 'news/news.html', context)

begin_with_yourself/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreatForm


class SignUp(CreateView):
    """Страница регистрации."""
    form_class = CreatForm

    success_url = reverse_lazy('main:index')

    template_name = 'users/signup.html'

begin_with_yourself/templates/about/author.html
{% extends 'base.html' %}

begin_with_yourself/templates/about/instruction.html
{% extends 'base.html' %}

{% block title %}
    Инструкция взаимодействия с сайтом.
{% endblock %}

{% block content %}
    <div class="container">
        <ul>
            <li>
                Регистрация.
            </li>
        </ul>
    </div>
{% endblock %}

begin_with_yourself/templates/about/tech.html
{% extends 'base.html' %}

begin_with_yourself/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/logo.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}"> 
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">  
    <meta name="msapplication-TileColor" content="#000"> 
    <meta name="theme-color" content="#ffffff">
    <script src="https://cdn.jsdelivr.net/npm/leaflet@1.6.0/dist/leaflet.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet@1.6.0/dist/leaflet.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/python-visualization/folium/folium/templates/leaflet.awesome.rotate.min.css"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}Главная страница.{% endblock %}</title>
</head>
<body>
    <header>
        {% include 'includes/header.html' %}
    </header>
    <main>
        {% block content %}
          Здесь пока ничего нет...
        {% endblock %}
    </main>
    <footer>
        {% include 'includes/footer.html' %}
    </footer>
</body>
</html>

begin_with_yourself/templates/includes/footer.html
<section class="">
  <!-- Footer -->
  <footer class="bg-secondary text-white">
    <!-- Grid container -->
    <div class="container p-4">
      <!--Grid row-->
      <div class="row">
        <!--Grid column-->
        <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
          <h5 class="text-uppercase">Начни с себя.</h5>

          <p>
            Сервис предназначен для удобного внесения своих проектов и идей на общее рассмотрение и помощь в обращении в органам власти.
          </p>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Информация.</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a href="{% url 'about:author' %}" class="text-white">Об авторе</a>
            </li>
            <li>
              <a href="{% url 'about:tech' %}" class="text-white">Технологии</a>
            </li>
            <li>
              <a href="#!" class="text-white">Пользовательское соглашение</a>
            </li>
            <li>
              <a href="{% url 'about:instruction' %}" class="text-white">Инструкция</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase mb-0">Контакты.</h5>

          <ul class="list-unstyled">
            <li>
              <a class="text-white" href="tel:+79128009285"></i> + 7 912 800 92 85</a>
            </li>
            <li>
              <a class="text-white" href="mailto:knigencev2003@gmail.com" target="_blank">knigencev2003@gmail.com</a>
            </li>
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      <p>© {{ year }} Copyright <span style="color:red">BWY</span></p>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->
</section>

begin_with_yourself/templates/includes/header.html
{% with request.resolver_match.view_name as view_name %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="{% url 'main:index' %}">
        {% comment %}<img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">{% endcomment %}
        <span style="color:green">BE</span>GIN WITH <span style="color:green">YOURSELF</span>
      </a> 

      <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'news:news' %}">Новости</a>
        </li> 
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:map' %}">Карта</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'main:create_idea' %}active{% endif %}" href="{% url 'main:create_idea' %}">Новый проект</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'main:profile' %}active{% endif %}" href="{% url 'main:profile' user.id %}"><span style="color:green;">Мой профиль</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
        </li> 
        {% else %}
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'users:login' %}active{% endif %}" href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'users:signup' %}active{% endif %}" href="{% url 'users:signup' %}">Зарегистрироваться</a>
        </li> 
        {% endif %}
      </ul>
    </div>
  </nav>
{% endwith %}

begin_with_yourself/templates/includes/mapFolium.html
<!DOCTYPE html>
<head>    
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    
        <script>
            L_NO_TOUCH = false;
            L_DISABLE_3D = false;
        </script>
    
    <style>html, body {width: 100%;height: 100%;margin: 0;padding: 0;}</style>
    <style>#map {position:absolute;top:0;bottom:0;right:0;left:0;}</style>
    <script src="https://cdn.jsdelivr.net/npm/leaflet@1.6.0/dist/leaflet.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet@1.6.0/dist/leaflet.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.css"/>
    <link rel="stylesheet" href="https://code.jquery.com/jquery-1.12.4.min.js"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/python-visualization/folium/folium/templates/leaflet.awesome.rotate.min.css"/>
    
            <meta name="viewport" content="width=device-width,
                initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
            <style>
                #map_9a33a2bc189fa36d9a3df2b3e34efad9 {
                    position: relative;
                    width: 100.0%;
                    height: 100.0%;
                    left: 0.0%;
                    top: 0.0%;
                }
            </style>
        
</head>
<body>    
    
            <div class="folium-map" id="map_9a33a2bc189fa36d9a3df2b3e34efad9" ></div>
        
</body>
<script>    
    
            var map_9a33a2bc189fa36d9a3df2b3e34efad9 = L.map(
                "map_9a33a2bc189fa36d9a3df2b3e34efad9",
                {
                    center: [56.828446, 60.637575],
                    crs: L.CRS.EPSG3857,
                    zoom: 11.5,
                    zoomControl: true,
                    preferCanvas: false,
                }
            );

            

        
    
            var tile_layer_3cf1231a58d1fd5336d27d1d7d679352 = L.tileLayer(
                "https://cartodb-basemaps-{s}.global.ssl.fastly.net/dark_all/{z}/{x}/{y}.png",
                {"attribution": "\u0026copy; \u003ca href=\"http://www.openstreetmap.org/copyright\"\u003eOpenStreetMap\u003c/a\u003e contributors \u0026copy; \u003ca href=\"http://cartodb.com/attributions\"\u003eCartoDB\u003c/a\u003e, CartoDB \u003ca href =\"http://cartodb.com/attributions\"\u003eattributions\u003c/a\u003e", "detectRetina": false, "maxNativeZoom": 18, "maxZoom": 18, "minZoom": 0, "noWrap": false, "opacity": 1, "subdomains": "abc", "tms": false}
            ).addTo(map_9a33a2bc189fa36d9a3df2b3e34efad9);
        
    
            var marker_d7f48293294a827c6099e04b666bbd3f = L.marker(
                [56.840179, 60.647049],
                {"color": "gray", "fillColor": "gray", "fillOpacity": 0.9, "radius": 9}
            ).addTo(map_9a33a2bc189fa36d9a3df2b3e34efad9);
        
    
        var popup_06dde6a306f23bb0099e22a2d3eee87b = L.popup({"maxWidth": "100%"});

        
            var html_b4d418e49a1787b18546efe11c3eec10 = $(`<div id="html_b4d418e49a1787b18546efe11c3eec10" style="width: 100.0%; height: 100.0%;">аррарарра</div>`)[0];
            popup_06dde6a306f23bb0099e22a2d3eee87b.setContent(html_b4d418e49a1787b18546efe11c3eec10);
        

        marker_d7f48293294a827c6099e04b666bbd3f.bindPopup(popup_06dde6a306f23bb0099e22a2d3eee87b)
        ;

        
    
    
            var marker_bc3f8fbba19bd0163a7067c8444ff4d2 = L.marker(
                [55.1, 0.5],
                {"color": "gray", "fillColor": "gray", "fillOpacity": 0.9, "radius": 9}
            ).addTo(map_9a33a2bc189fa36d9a3df2b3e34efad9);
        
    
        var popup_e906379b3c54416217a00c0f7af0617f = L.popup({"maxWidth": "100%"});

        
            var html_f831e6454eee7fb7e9324f6e5c5ff865 = $(`<div id="html_f831e6454eee7fb7e9324f6e5c5ff865" style="width: 100.0%; height: 100.0%;">jjfjfj</div>`)[0];
            popup_e906379b3c54416217a00c0f7af0617f.setContent(html_f831e6454eee7fb7e9324f6e5c5ff865);
        

        marker_bc3f8fbba19bd0163a7067c8444ff4d2.bindPopup(popup_e906379b3c54416217a00c0f7af0617f)
        ;

        
    
</script>

begin_with_yourself/templates/includes/paginator.html
{% if page_obj.has_other_pages %} 
<nav aria-label="Page navigation" class="my-5"> 
  <ul class="pagination"> 
    {% if page_obj.has_previous %} 
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li> 
      <li class="page-item"> 
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая 
        </a> 
      </li> 
    {% endif %} 
    {% for i in page_obj.paginator.page_range %} 
        {% if page_obj.number == i %} 
          <li class="page-item active"> 
            <span class="page-link">{{ i }}</span> 
          </li>
        {% else %} 
          <li class="page-item"> 
            <a class="page-link" href="?page={{ i }}">{{ i }}</a> 
          </li> 
        {% endif %} 
    {% endfor %} 
    {% if page_obj.has_next %} 
      <li class="page-item"> 
        <a class="page-link" href="?page={{ page_obj.next_page_number }}"> 
          Следующая 
        </a> 
      </li>
      <li class="page-item"> 
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

begin_with_yourself/templates/main/create_idea.html
{% extends 'base.html' %}

{% load user_filters %} 

{% block title %}
    Создание новой идеи.
{% endblock %}

{% block content %}
<div class="container py-5"> 
    <div class="row justify-content-center"> 
      <div class="col-md-8 p-5"> 
        <div class="card"> 
          <div class="card-header">        
            Новый пост              
          </div> 
          <div class="card-body"> 
            {% if form.errors %} 
                {% for field in form %} 
                    {% for error in field.errors %}             
                        <div class="alert alert-danger"> 
                            {{ error|escape }} 
                        </div> 
                    {% endfor %} 
                {% endfor %} 
                {% for error in form.non_field_errors %} 
                    <div class="alert alert-danger"> 
                        {{ error|escape }} 
                    </div>
                {% endfor %}
            {% endif %}         
            <form method="post" action="{% url 'main:create_idea' %}">
              {% csrf_token %} 
              {% for field in form %}           
                <div class="form-group row my-3 p-3"> 
                  <label for="{{ field.id_for_label }}"> 
                    {{ field.label }} 
                    {% if field.field.required %} 
                      <span class="required text-danger">*</span> 
                    {% endif %} 
                  </label> 
                  {{ field|addclass:'form-control' }} 
                  {% if field.help_text %} 
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted"> 
                    {{ field.help_text|safe }} 
                  </small>
                {% endif %}              
                </div> 
              {% endfor%} 
              <div class="d-flex justify-content-end"> 
                <button type="submit" class="btn btn-primary"> 
                  {% if is_edit %} 
                    Сохранить 
                  {% else %} 
                    Добавить 
                  {% endif %}                
                </button>  
              </div> 
            </form>
          </div> 
        </div> 
      </div> 
    </div> 
</div>
{% endblock %}

begin_with_yourself/templates/main/idea_detail.html
{% extends 'base.html' %}

{% block title %}
    Проект {{ post.text|slice:"30" }}
{% endblock %}

{% block content %}
<div class="row"> 
    <aside class="col-12 col-md-3"> 
    <ul class="list-group list-group-flush"> 
        <li class="list-group-item"> 
          Дата публикации: {{ post.pub_date|date:"d E Y" }} 
        </li> 
        <li class="list-group-item"> 
            Автор: {{ post.author }} 
        </li> 
        <li class="list-group-item d-flex justify-content-between align-items-center"> 
            Всего постов автора:  <span>{{ post.author.ideas.count }}</span> 
        </li> 
        <li class="list-group-item"> 
            <a href="{% url 'main:profile' post.author.username %}">все посты пользователя</a> 
        </li> 
    </ul> 
    </aside> 
    <article class="col-12 col-md-9"> 
    <p> 
        {{ post.text }} 
        {% if request.user.username == post.author.username %} 
            <a class="btn btn-primary" href="{% url 'main:idea_edit' post.author.id %}"> 
                редактировать запись 
            </a>
        {% endif %}             
    </p> 
    </article> 
</div>
{% endblock %}

begin_with_yourself/templates/main/index.html
{% extends 'base.html' %}

{% block title %}
    Главная страница.
{% endblock %}

{% block content %}
    <div class="container">
        <hr>
        <h1>
            Начните с себя.
        </h1>
        <h2>
            А мы вам в этом поможем.
        </h2>
        <hr>
    </div>
{% endblock %}

begin_with_yourself/templates/main/map.html
{% extends 'base.html' %}

{% block title %}
    Главаная страница.
{% endblock %}

{% block script %}
<script>
    L_NO_TOUCH = false;
    L_DISABLE_3D = false;
</script>
{% endblock %}

{% block content %}
    <div id="map-folium">
        {% include 'includes/mapFolium.html' %}
    </div>
{% endblock %}

{% block basescript %}
{% endblock %}

begin_with_yourself/templates/main/profile.html
{% extends 'base.html' %}

{% block title %}
    {{ user.username }}
{% endblock %}

{% block content %}
    <div class="container">
        <h1>
            Страница пользователя {{ user.username }}.
        </h1>
        <button type="button" class="btn btn-outline-success">Настройки</button>
        {% for idea in page_obj %}
          <article>
            <ul>
                <li> 
                  Автор: 
                  {{ idea.author.get_full_name }}
                </li>
                <li>
                  Дата публикации:
                  {{ idea.pub_date|date:"d E Y" }}
                </li>
            </ul>
            <p>
              {{ idea.text }}
            </p>
            <a href="{% url 'main:idea_detail' idea.id %}">подробная информация</a>
          </article> 
          {% if not forloop.last %} 
            <hr>
          {% endif %} 
        {% endfor %}
        {% include 'includes/paginator.html' %}
    </div>
{% endblock %}

begin_with_yourself/templates/news/news.html
{% extends 'base.html' %}

{% block title %}
    Страница последних новостей.
{% endblock %}

{% block content %}
    <div class="container">
        <h1>
            Последние новости.
        </h1>
        {% for idea in page_obj %}
            <article>
                {{ idea.text }}
            </arcticle>
            {% if not forloop.last %}
                <hr>
            {% endif %}
        {% endfor %}
        {% include 'includes/paginator.html' %}
    </div>
{% endblock %}

begin_with_yourself/templates/users/signup.html
{% extends 'base.html' %}

{% load user_filters %}

{% block title %}
    Зарегистрироваться.
{% endblock %}

{% block content %}
<div class="row justify-content-center"> 
    <div class="col-md-8 p-5"> 
      <div class="card"> 
        <div class="card-header">Зарегистрироваться</div> 
          <div class="card-body"> 
          {# Загружаем фильтры #} 
              {% if form.errors %} 
                  {% for field in form %}  
                    {% for error in field.errors %}             
                      <div class="alert alert-danger"> 
                        {{ error|escape }} 
                      </div> 
                    {% endfor %} 
                  {% endfor %}
                  {% for error in form.non_field_errors %} 
                    <div class="alert alert-danger"> 
                      {{ error|escape }} 
                    </div>
                  {% endfor %}
              {% endif %}
              <form method="post" action="{% url 'users:signup' %}"> 
                {% csrf_token %}
                {# Выводим поля в цикле, по отдельности #} 
                {% for field in form %}  
                  <div class="form-group row my-3"> 
                    <label for="{{ field.id_for_label }}"> 
                      {{ field.label }} 
                        {% if field.field.required %} 
                          <span class="required text-danger">*</span> 
                        {% endif %}
                    </label>
                    {# К полю ввода добавляем атрибут class #} 
                    {{ field|addclass:'form-control' }}
                      {% if field.help_text %} 
                        <small 
                          id="{{ field.id_for_label }}-help" 
                          class="form-text text-muted" 
                        > 
                          {{ field.help_text|safe }} 
                        </small> 
                      {% endif %} 
                  </div> 
                {% endfor %}
              <div class="col-md-6 offset-md-4"> 
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card --> 
      </div> <!-- col -->
  </div> <!-- row --> 
{% endblock %}